version: '3'
services:
  jenkins:
    build:
      context: docker/
    ports:
      - "8080:8080"
    #tty: true
    privileged: true
    volumes:
      # Mound docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Mound seed workspace
      # Makes workspace own by root ((
      #- .:/var/jenkins_home/workspace/seed:ro
    environment:
      - HOST_HOME=$HOME
#volumes:
#  jenkinshome: {}